name: GitHub - Action Lint
on:
  push:
    paths:
      - ".github/workflows/**"
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: raven-actions/actionlint@3a24062651993d40fed1019b58ac6fbdfbf276cc #v2.0.1
