name: Rust - Lint
on:
  push:
    paths-ignore:
      - ".github/workflows/**"
      - ".gitignore"
      - "README.md"
jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: clippy, rustfmt
      - name: "Run Rust lint"
        run: "make lint"
